# Generated by Django 4.2.6 on 2023-11-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPessoa',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_comp', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
                ('endereco_cep', models.IntegerField()),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=60)),
                ('nome_rua', models.CharField(max_length=100)),
                ('nm_casa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CadastroSala',
            fields=[
                ('nome', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('lugares', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('data', models.DateField(null=True)),
                ('locatario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva_sala.cadastrosala')),
            ],
        ),
    ]
